### ISSUE TITLE
Default CSS does not work well for inline CSS

### ISSUE THREAD

**Issue by JensRantil** [select2/select2#1031]
When putting a select2 element inline in a text,

``` css
.select2-container {
    ...
    vertical-align: top;
}
```

CSS property makes the select box align fairly ugly to the text. See http://jsfiddle.net/7cmZ2/2/. Changing it to

``` css
.select2-container {
    ...
    vertical-align: middle;
}
```

make vertical align much more balanced. See http://jsfiddle.net/7cmZ2/3/.

It seems that the `vertical-align` was added due to #266. Since the fiddle there can't reproduce the initial bug, I'm not sure if simply adding a vertical align solved the bug, or if it needs to have the value `top`.
