### ISSUE TITLE
Offscreen css overflow

### ISSUE THREAD

**Issue by kvpt** [select2/select2#1074]
The select2-offscreen class causes overflow-x on Chrome.
I fix it by replace height, width and margin by 0.
I dont know if there was a reason to set theses properties to 1px, but it appear to works fine for me.

``` css
.select2-offscreen {
    border: 0;
    clip: rect(0 0 0 0);
    height: 0;
    margin: 0;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 0;
}
```
