### ISSUE TITLE
Dropdown doesn't close on blur

### ISSUE THREAD

**Issue by webberig** [select2/select2#1089]
Hi,

I've setup a multi-select that uses Ajax to retrieve data from the server. If you click on the text input, you get the dropdown menu with the text "Please enter 1 more character". This box doesn't seem to close if you click away on the page and trigger the blur event.

Fiddle: http://jsfiddle.net/dGF4W/
(obviously the ajax call will fail in the example)

Strangely enough, this doesn't seem to be an issue on the demo page, but I can't seem to find what I'm doing wrong...

**Comment by NoelBaron** [comment]
I will second @stephenoldham. I had the same issue, applied CSS rules to account for custom z-index, and suddenly select2 was disappearing on blur again. Worked like a charm with the following code. 

```css
.select2-container {
  z-index: 6000;
}
.select2-drop-mask {
  z-index:5990;
}
.select2-drop-active {
  z-index:5995;
}
```
