### ISSUE TITLE
select2-search-choice-close

### ISSUE THREAD

**Issue by hisapy** [select2/select2#1202]
Hello ivayberg

I was trying out select2 3.3.2 multiple select but strangely the close icon of a selected item wasn't displaying at all in Google Chrome. In Firefox there were no problems. After debugging your code I changed the font-size property in the .select2-search-choice-close CSS rule as follows

``` css
.select2-search-choice-close {
    display: block;
    width: 12px;
    height: 13px;
    position: absolute;
    right: 3px;
    top: 4px;

    font-size: 1px;
    outline: none;
    background: url('select2.png') right top no-repeat;
}
```

to 

``` css
.select2-search-choice-close {
    display: block;
    width: 12px;
    height: 13px;
    position: absolute;
    right: 3px;
    top: 4px;

    font-size: 2px;
    outline: none;
    background: url('select2.png') right top no-repeat;
}
```

and now everything is working fine in both browsers, and Safari. 

I just wanted to let you know in case you didn't know it already.
