### ISSUE TITLE
convert select2.css to SASS

### ISSUE THREAD

**Issue by paprikka** [select2/select2#1507]
Well, it would be nice to have a configurable version of the plugin's CSS. I'm not talking about advanced customization, such as size and layout, but file paths, borders and (maybe) colours. Just to make myself clear here: I don't think we should sacrifice quality for flexibility. I just want to make this easier to maintain in bigger projects.

An exported css file would be still treated as default, but more advanced users, or someone who wants to include Select2.js via a package manager (eg. Bower.io) would be able to preserve separation of vendor and app sources.

``` scss
background-image: url('select2x2.png')

// will become
$img-base-url: '../path/to/something/';

// several lines later
background-image: image-url("#{$img-base-url}select2x2.png")
```

I could code it and push a PR in 7-10 days if you want to, but I need to know if it makes any sense for you guys.
