### ISSUE TITLE
How to disable "No matches found" and autocomplete at all on select2/Tagging Support?

### ISSUE THREAD

**Issue by Artgit** [select2/select2#1657]
Hello, 

How to disable "No matches found" and autocomplete at all on select2/Tagging Support?

Thanks

**Comment by cesarmorales** [comment]
Great!!

**Comment by a2net** [comment]
You can just put this in your css

span.select2-search.select2-search--dropdown{display:none;}

**Comment by cesarmorales** [comment]
????

**Comment by helmidridi** [comment]
.select2-no-results {
    display: none !important;
}

**Comment by plentz** [comment]
```css
.select2-results__message {
  display: none !important;
}
```
