### ISSUE TITLE
Default placeholders shown in grey – control looks like it's disabled

### ISSUE THREAD

**Issue by ujay68** [select2/select2#1829]
By default, select shows its default placeholders http://ivaynberg.github.io/select2/#placeholders in grey:

``` css
.select2-default {
  color: #999 !important;
}
```

We've done some user testing, and we've heard this is irritating because the control then looks like it's disabled.
