### ISSUE TITLE
SASS error on select2-ng (4.0.0) version

### ISSUE THREAD

**Issue by iamnewton** [select2/select2#2896]
```
www/vendor/select2/src/scss/_single.scss:21: Base-level rules cannot contain the parent-selector-referencing character '&'. (Sass::SyntaxError)
```

Change:

``` scss
&[dir="rtl"] {
    .select2-selection--single {
        .select2-selection__rendered {
            padding-right: 8px;
            padding-left: 20px;
        }
    }
}
```

to

``` scss
[dir="rtl"] {
    .select2-selection--single {
        .select2-selection__rendered {
            padding-right: 8px;
            padding-left: 20px;
        }
    }
}
```

**Note:** removing the `&` fixes it and doesn't appear to break any CSS.
