### ISSUE TITLE
Placeholder width cutting off text when Select2 is initialized inside a hidden element

### ISSUE THREAD

**Issue by yeago** [select2/select2#291]
We're having to patch select2 like so to get our placeholder text to appear properly.
- ln 345: width: auto !important;

This happens when the new width option is either not provided or is set to 'element'. The placeholder gets an inline css width set, which mysteriously goes away and never comes back when the input is interacted with.

**Comment by r-nicol** [comment]
I am also seeing this issue even when the element is active and shown. It sets the inner select2-search__field to like 35px for me. My temp solution was a modified version of @jgeurts solution

.select2-container .select2-search__field {
    width: 100% !important;
}
This works for version 4.0.0.

**Comment by pjclas** [comment]
The above didn't work for me, I had to add the containing \<li\> as well:
```CSS
    .select2-container .select2-search, 
    .select2-container .select2-search__field {
        width: 100% !important;
    }
```

The problem is now the search field drops to the next line after you've added an element...

**Comment by r-nicol** [comment]
I take that back, the whole multi select is just a mess for me on closer inspection. Overflows, dropdown is partial covered. I am guessing some other styles are breaking it, but nothing jumps out. I only have generic reset styles applying. I will strip the CSS I have back to see what is playing with it.

**Comment by tylik1** [comment]
Ran into the same issue by setting width of multiselect to 100%
This css  fixed the issue

.select2-container .select2-search__field:not([placeholder = '']) {
    width: 100%!important;
}

The css will set input width to 100% only if placeholder attribute value is not empty.

**Comment by leonwolfus** [comment]
I found the following way for my multiselect with hidden input: 
```css
.select2-container.select2-container-multi .select2-choices .select2-search-field:first-child {
     width: 100% !important;
}
```
it sets 100% only in case of there is no choises.
