### ISSUE TITLE
Tabindex is missing for multiple select + different focus behavior

### ISSUE THREAD

**Issue by ova2** [select2/select2#3031]
If we set ```tabindex``` on native HTML select element with **single** selection, say ```tabindex="395"```, it is rendered in the ```span``` element with the class ```select2-selection__rendered```.

```html
<span class="select2-selection__rendered" id="..." tabindex="395">
    <span class="option-text">...</span>
</span>
```

This ```span``` is focusable and we can style the focusable element with CSS. E.g. like bootstrap focus

```css
.select2-container--default .select2-selection--multiple:focus {
    border-color: rgba(82, 168, 236, .8) !important;
    outline: 0 !important;
    outline: thin dotted !important \9;
    -moz-box-shadow: 0 0 8px rgba(82, 168, 236, .6) !important;
    box-shadow: 0 0 8px rgba(82, 168, 236, .6) !important;
}
```

If we set ```tabindex``` on native HTML select element with **multipe** selection, it is nowhere rendered. Navigation with tab is problematic (right tab sequence is not always correct). I tried to style the focusable element for multiple select2. It's tricky. These settings works

```css
.select2-container--default .select2-selection--multiple:focus {
    border-color: rgba(82, 168, 236, .8) !important;
    outline: 0 !important;
    outline: thin dotted !important \9;
    -moz-box-shadow: 0 0 8px rgba(82, 168, 236, .6) !important;
    box-shadow: 0 0 8px rgba(82, 168, 236, .6) !important;
}

.select2-container--default .select2-selection--multiple:focus .select2-selection__rendered {
    border-color: rgba(82, 168, 236, .8) !important;
}
```

but there are different behaviors between single and multiple selections:

1. Click onto the select field. Dropdown gets open.
 * Single selection - focus appears on the select field.
 * Multiple selection - focus disappear on the select field.
2. Select an item in the dropdown. Dropdown gets closed.
 * Single selection - focus disappears on the select field.
 * Multiple selection - focus appears on the select field.

Could you please add configured ```tabindex``` to the rendered ```span``` element with class ```select2-container--default .select2-selection--multiple```? I'm not sure, but I think it could solve some problems. Can you also check mentioned different behaviors please?

**EDIT:** tabindex for single select is not set too. I set it programmatically :-) It works for single select. But I can not do the same for multi select because no ID for the ```span``` with ```class select2-container``` is set. Native select has an ID of course, but I don't see any IDs in the generated markup of multi Select2.
