### ISSUE TITLE
How to remove instead of gray out item from dropdown when its selected 

### ISSUE THREAD

**Issue by Exerlol** [select2/select2#3046]
Hey, first of all, gr8 plugin...I used select2 3,4,1, and in that version, when you select item, it was removed from drop down...now its just grayed out...Is there a way to remove it instead of gray it out? Thanks in advance

**Comment by kevin-brown** [comment]
There's a `classic` theme that you can use you get back then old theme, which includes hiding selected options for multiple select dropdowns.

https://select2.github.io/examples.html#themes

You can also just hide the selected options with

```css
.select2-results__option--highlighted[aria-selected=true] {
  display: none;
}
```
