### ISSUE TITLE
Render native select out of screen or with clip: rect(0 0 0 0), height: 0

### ISSUE THREAD

**Issue by ova2** [select2/select2#3065]
I realized a probelm with Select2 when using with some web framworks having client-side validation. Some frameworks use this selector to figure out elements to be validated while form submission: ```input:visible:enabled:not(:button)[name]```. Saidly, but the native select element in Select2 has ```display: none``` and can not be validated. Can you render the native select out of screen please or apply this jQuery UI style class (normally applied to the surrounded div)?

```css
.ui-helper-hidden-accessible {
    border: 0;
    clip: rect(0 0 0 0);
    height: 0px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 0px;
}
```

I quess, you should also set ```aria-hidden``` attr. to make it invisible for screen readers.
