### ISSUE TITLE
Table Cell Alignment of Select2 Input Field in IE8

### ISSUE THREAD

**Issue by ghost** [select2/select2#320]
FF and Chrome (displays correctly):

![FF and Chrome](http://i.imgur.com/UAKMD.png)

IE8 (displays incorrectly):

![IE8](http://i.imgur.com/81ppq.png)

``` html
            <table border="0" cellspacing="0" cellpadding="0" class="inputs" id="inputs">
              <tbody>
              <tr class="inputs-template">
                <td>
                  <select name="filter-object" id="filter-object" class="ui-widget ui-state-default ui-corner-all">
                    <option value=""> </option>
                  </select>
                </td>
                <td>
                  <select name="filter-relation" id="filter-relation" class="ui-widget ui-state-default ui-corner-all">
                    <option value=""> </option>
                  </select>
                </td>
                <td>
                  <input type="hidden" name="filter-value" id="filter-value" class="ui-widget ui-state-default ui-corner-all"
                    style="width:225px" />
                </td>
              </tr>
            </tbody>
            </table>
```

CSS:

``` css
tr.inputs-template {
  margin: 0;
  padding: 0;
  visibility: hidden;
  display: none;
}

table.inputs {
  border-spacing: 0;
  border-collapse: collapse;
  margin: 0;
  padding: 0;
}

table.inputs td {
  margin: 0;
  padding: 0 0.25em 0 0; /* top, right, bottom, left */
  vertical-align: middle;
}
```

JavaScript:

``` javascript
  var inputs = $('tr.inputs').filter( ':last' );
  var filterValue = $(inputs).find( '#filter-value' );

  filterValue.select2({
    minimumInputLength: 0,
    initSelection: function( element, callback ) {
      return $.getJSON(
        MAP_SERVER_SERVICE + 'search?o=' + filterObject.val() + '&r=' + filterRelation.val() + '&v=', null, function( data ) {
        if( $.isFunction( callback ) ) {
          return callback( data );
        }
      })
    },
    ajax: {
      url: MAP_SERVER_SERVICE + 'search',
      dataType: 'json',
      data: function( term, page ) {
        return {
          o: filterObject.val(),
          r: filterRelation.val(),
          v: term
        };
      },
      results: function( data, page ) {
        return { results: data };
      }
    },
    minimumResultsForSearch: 15,
    formatResult: filterFormatResult,
    formatSelection: filterFormatSelection
  });
```

Cloning code:

``` javascript
    var row = $('tr.inputs-template');
    var clone = row.clone( true, false );
    clone.attr( 'class', 'inputs' );
    $('table#inputs > tbody:last').append( clone );
```

This code copies the template table row to a new table row, and switches the class to make it visible. That's a bit beside the point, I think. The result is that the DIV tags added to the DOM by the Select2 code insert lots of top padding (or margins?) in IE8. Consequently, this creates differences in IE8 vs. Firefox/Chrome, as shown in the images above.

I have not looked into a fix at this time.
