### ISSUE TITLE
Can't seem to overwrite the style

### ISSUE THREAD

**Issue by stefkosmo** [select2/select2#3268]
Hi,

I've added

``` css
.select2-container--default .select2-results__option--highlighted[aria-selected] {
  background-color: #ffffff;
  color: white;
}
```

to my sass file which is being loaded after select2 css, and it's not overwriting the blue aria-selected property?

Any ideas?

Thanks
