### ISSUE TITLE
Cursor does not change to default in disabled options

### ISSUE THREAD

**Issue by xforceco** [select2/select2#3700]
I am using select 3.5.3, and I notice that cursor does not change to default cursor when hovering on a disabled option.

My browser is chrome  44.0.2403.155.

It is reproducible at demo page (Disabled Options): http://select2.github.io/select2/

**Comment by kevin-brown** [comment]
At this point it's probably not something that's going to be fixed in a future 3.x release, though it was fixed in 4.0.0.

Here's some CSS you can use to fix the issue

```css
.select2-disabled .select2-result-label {
  cursor: default;
}
```
