### ISSUE TITLE
Safari 9 Search field

### ISSUE THREAD

**Issue by vdclouis** [select2/select2#3738]
this needs to be added to make sure this input has no border in Safari 9

```css
.select2-container--default .select2-search--inline .select2-search__field {
    -webkit-appearance: none;
}
```
