### ISSUE TITLE
Multiple Select: Selected Option not removed from Options since 4.0

### ISSUE THREAD

**Issue by krisdigital** [select2/select2#3850]
On the Demo-Page, after selecting "Alaska" from the dropdown in the multiple select demo, Alaska is still under the options. If selected again, it is removed from the selected tags..

A quick fix:

```css
[aria-selected="true"] {
  display:none;
}
```
