### ISSUE TITLE
Selections going outside input when more selected

### ISSUE THREAD

**Issue by mariaczi** [select2/select2#3922]
Hi,

I cannot solve it by myself.
I was surprised but when I choose to many options, it's going into new line, outside input.
Currently - looks really bad. You can easily recreate it on e.g. this tempalte demo page: http://seantheme.com/color-admin-v1.9/admin/html/form_plugins.html .
![2lines](https://cloud.githubusercontent.com/assets/9385106/11095778/942e9400-888e-11e5-9e8e-0e29ae0f1a44.png)

**Comment by kevin-brown** [comment]
This is usually a pretty good indicator that the theme is overriding something that it shouldn't be. In this case, it's the height of the selection for multiple selects.

```css
.select2-container .select2-selection--single, .select2-container--default .select2-selection--multiple {
    height: 34px!important;
    border-color: #e2e7eb!important;
}
```

Removing the `height` rule for multiple selects fixes the issue.
