### ISSUE TITLE
features copyable multi and horizontal extending when many...

### ISSUE THREAD

**Issue by joomlaA1** [select2/select2#3987]
1: multiselect2 - copyable [x option1]  [x option2] then pastable also like [x option1]  [x option2]

2: multiselect2 - current: when many, goes down to nextline. wish: horizontal extension(like a normal input when many are typed)

**Comment by joomlaA1** [comment]
hello :)

**Comment by kevin-brown** [comment]
1. Right now [there is a bug](https://github.com/select2/select2/issues/3458) with pasting that is preventing it from automatically converting the pasted text to tags. Note that Select2 does not support copying out of the selection area by default because this is not normally the expected behaviour of select boxes.

  You can override this with the following CSS:

  ```css
  .select2-container .select2-selection--multiple {
    user-select: initial;
    -webkit-user-select: initial;
  }

  .select2-selection__choice__remove {
    user-select: none;
    -webkit-user-select: none;
  }
  ```

2. This is something that has been asked a few times, but for some reason I can't find a duplicate to point this at. Basically look around for how to make Select2 display on a single line, or how to make it scroll horizontally, and you should find one of the many possible hacks.
