### ISSUE TITLE
changing position of the clear button

### ISSUE THREAD

**Issue by thadeu** [select2/select2#4128]
#### Position button clear from Right select2

``` css
.select2-selection__clear{
   position: absolute;
   top: 0;
   right: -33px;
   border: 1px solid #ccc;
   border-left: 0;
   height: 100%;
   padding: 0 12px;
}
```
