### ISSUE TITLE
Fix placeholder contrast in modern default theme

### ISSUE THREAD

**Issue by mcandre** [select2/select2#5649]
The placeholder style resembles the style for actual values too closely.

# Workaround A

Configure the classic theme.

# Workaround B

Write custom CSS on top of the default theme:

```css
.select2-selection__placeholder {
    font-size: 0.8em;
    font-style: italic;
}
```
