### ISSUE TITLE
Dependency on bootstrap styles

### ISSUE THREAD

**Issue by leesei** [select2/select2#929]
I'm not sure if it is intended or accidental that select2 depends on bootstrap.
Anyway I'm using select2 (thanks for the great plugin btw) without bootstrap.css, but my options under optarg are over-indented. See comparison with the examples on project page:
![20130224 030600](https://f.cloud.github.com/assets/544400/188447/862063c4-7ded-11e2-9516-337bc051e001.png)
Took me some time comparing the styles in debugger to figure out that the padding-left rule was set by bootstrap but not select2.

Here is the fix:

``` css
  .select2-results ul.select2-result-sub {
      margin: 0;
+     padding-left: 0;
  }
```

Sorry for not making this a pull request
